name: RareItems2
main: com.gmail.ne0nx3r0.rareitems.RareItems
version: '0.2.1'
database: false
description: Rare Items v2 (the re-rewrite)
commands:
    ri:
      description: RareItems command interface